# Permalinks
permalink:        pretty

# Setup
title:            despat
tagline:          ''
description:      'a Mobile Object Detection Tool for Urban Surveys'
url:              / 
baseurl:          / #http://localhost:4000

author:
  name:           'Christopher Getschmann'
  url:            http://volzo.de

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/volzotan/despat

theme: jekyll-theme-minimal